# Generated by Django 3.1.10 on 2021-05-19 07:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('todos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='todos',
            options={'verbose_name': 'Todo', 'verbose_name_plural': 'Todos'},
        ),
        migrations.AlterField(
            model_name='todos',
            name='deadline',
            field=models.DateTimeField(),
        ),
    ]
